### ISSUE TITLE
update Readme and others

### ISSUE THREAD

**Issue by OlliesWorld** [postmanlabs/open-technologies-docs#8]
ReadMe, Contributing, code of conduct need to be updated with Open tech policy/proceedures

**Comment by pavandeore** [comment]
hey so in readme, where you have git clone command right,you can add postman-docs at the ending
as on the next line it is mentioned 
`cd postman-docs`   so indirectly means clone repo into postman-docs  

like this
`git clone https://github.com/postmanlabs/open-technologies-docs.git postman-docs`
